import {
    existsSync,
    readFileSync,
    unlinkSync,
} from "fs";
import { isErrorOfNotFound, PagePluginConfig, ColoringConsole, MergedPluginOption } from "./types";
import { EntryPath } from "./core";
import path from "path";
import { pathToFileURL } from "url";

const _console = new ColoringConsole(1)
const GENERATED_FLAG = "<!--This is generated by vite-plugin-auto-mpa-html.-->"

/**
 * Resolve the virtual HTML entry path.
 *
 * The special ".html" value flattens `page/main.js` to `page.html`, so its
 * virtual entry must live beside the page directory rather than inside it.
 */
export function resolveEntryTemplatePath(entry: EntryPath): string {
    return entry.__options.templateName === '.html'
        ? `${entry.abs}.html`
        : path.join(entry.abs, entry.__options.templateName)
}

export const __defaultHTMLTemplate = `<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <link rel="icon" type="image/icon" href="/favicon.ico" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    {{#if title}}<title>{{title}}</title>{{else}}<title>Application</title>{{/if}}
    {{#if description}}<meta name="description" content="{{description}}" />{{/if}}
    {{#if keywords}}<meta name="keywords" content="{{keywords}}" />{{/if}}
  </head>
  <body>
    <div id="app"></div>
  </body>
</html>`

export async function fetchTemplateHTML(
    entry: EntryPath,
    pageConfig: PagePluginConfig,
    pluginOptions: MergedPluginOption
) {
    let htmlContent;
    const templatePath = pageConfig.template 
        ? path.resolve(entry.abs, pageConfig.template)
        : resolveEntryTemplatePath(entry);
    try {
        htmlContent = readFileSync(
            templatePath,
            {
                encoding: "utf-8",
            }
        );
    } catch (e) {
        if (!isErrorOfNotFound(e)) throw e;
        _console.error(`Page entry "${entry.abs}", its template cannot be found, using default template as fallback! (${e.message})`)
        htmlContent = __defaultHTMLTemplate
    }
    htmlContent = await entry.__options.engine.render(htmlContent, {
        ...entry.__options.sharedData,
        ...pageConfig.data,
    }, {
        entry,
        pageConfig,
        pluginOptions,
        templatePath,
    });
    const generatedHtml = GENERATED_FLAG.concat(htmlContent).replace(
        "</html>",
        // FIXME: this line of rewrite entry module script is not perfect
        `<script type="module" src="${entry.__options.templateName.startsWith("/") ? `./${entry.__options.entryName}` : `./${path.basename(entry.value)}/${entry.__options.entryName}`}"></script></html>`
        // `<script type="module" src="${path.relative(root, entry.abs + '/' + entry.__options.entryName)}"></script></html>`
    );
    return generatedHtml
}

/**
 * generate entries for `rollupOptions.build.input`
 * @param entries {Entries}
 * @param dest {string} Output dir
 */
export async function prepareSingleVirtualEntry(entry: EntryPath, pluginOption: MergedPluginOption) {
    let pageData: PagePluginConfig = {}
    const configPath = path.join(entry.abs, entry.__options.configName);
    if (!existsSync(configPath)) {
        _console.fatal(`Page entry: ${entry.value}, its config (${entry.__options.configName}) cannot be found, please check!`)
        return "";
    }
    if (entry.__options.configName.endsWith('.json')) {
        const tmp = readFileSync(configPath, { encoding: "utf-8" })
        pageData = JSON.parse(tmp)
    } else if (entry.__options.configName.endsWith('.js')) {
        const config = await import(pathToFileURL(configPath).toString()).catch(e => {
            _console.error(e.message);
            return undefined;
        })
        if(config && config.default) {
            if(typeof config.default == "function") {
                pageData = await config.default(pluginOption)
            } else {
                pageData = config.default
            }
        } else {
            _console.error(`config file ${configPath} cannot be parsed and imported, maybe forgot exporting default?`)
            return "";
        }
    } else {
        _console.error(`using ${entry.__options.configName} as page config is not supported yet`)
        return "";
    }
    const generatedHtml = await fetchTemplateHTML(entry, pageData, pluginOption)
    const tplPath = resolveEntryTemplatePath(entry)
    if (existsSync(tplPath)) {
        const fileContent = readFileSync(tplPath, { encoding: "utf-8" });
        if (!fileContent.startsWith(GENERATED_FLAG)) {
            _console.warn(`There is a same named HTML file (${entry.__options.templateName}) already exist in entry '${entry.value}', template generation skipped`)
            return "";
        }
    }
    return generatedHtml;
}
export async function prepareVirtualEntries(
    entries: EntryPath[],
    pluginOption: MergedPluginOption
) {
    const virtualMap = new Map<string, string>();
    await Promise.all(entries.map(async entry => {
        const tplPath = resolveEntryTemplatePath(entry);
        const generatedHtml = await prepareSingleVirtualEntry(entry, pluginOption);
        virtualMap.set(tplPath, generatedHtml);
    }));
    return virtualMap;
}

export function cleanTempEntries(
    entries: EntryPath[],
) {
    // `buildEnd` will be called even build failed, so a throttle is needed.
    if (!entries || entries.length === 0) return;
    entries.forEach(k => {
        // generate temp entries for build
        const absTemplatePath = resolveEntryTemplatePath(k)
        if (existsSync(absTemplatePath)) {
            const tmp = readFileSync(absTemplatePath, { encoding: "utf-8" })
            if (tmp.startsWith(GENERATED_FLAG)) unlinkSync(absTemplatePath);
        }
    });
}
